"""Discovery pipeline orchestrator. Runs stages 2-5 for a resolved vendor,
writes: fixtures/vendor_catalogs/<slug>.yaml,
        ontology/proposed/<slug>.<report>.PROPOSED.yaml,
        out/discovery_reports/<slug>.md.
"""
from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
import yaml

from .cache import DiskCache
from .enrich.dedupe import dedupe_raw_fields
from .enrich.semantic_tag import tag_fields
from .enrich.trap_detect import detect_traps
from .enrich.unit_infer import infer_units
from .extract.html_structured import extract_html_structured
from .extract.markdown import extract_markdown
from .extract.openapi import extract_openapi
from .fetch.html import fetch_html_source
from .fetch.openapi import fetch_openapi_source
from .llm import LLMClient
from .mapper import propose_mapping
from .models import (
    EnrichedField, RawField, RegistrySource, SourceDoc, VendorRegistryEntry,
)
from .report import write_coverage_report


@dataclass
class PipelineResult:
    catalog_path: Path
    proposed_path: Path
    report_path: Path
    n_fields: int
    n_found: int


def _fetch(source: RegistrySource, cache: DiskCache) -> tuple[list[SourceDoc], dict]:
    status = {"url": source.url, "status": "ok", "pages": 0}
    try:
        if source.kind == "html_doc":
            docs = fetch_html_source(source, cache=cache)
        elif source.kind == "openapi":
            docs = fetch_openapi_source(source, cache=cache)
        else:
            docs = []
        status["pages"] = len(docs)
    except Exception as e:  # noqa: BLE001
        status["status"] = f"error: {e}"
        docs = []
    return docs, status


def _extract(docs: list[SourceDoc]) -> list[RawField]:
    out: list[RawField] = []
    for d in docs:
        if d.kind == "html":
            out.extend(extract_html_structured(d))
        elif d.kind == "markdown":
            out.extend(extract_markdown(d))
        elif d.kind == "openapi_schema":
            out.extend(extract_openapi(d))
    return out


def _enrich(raws: list[RawField]) -> list[EnrichedField]:
    fields = dedupe_raw_fields(raws)
    infer_units(fields)
    tag_fields(fields)
    detect_traps(fields)
    return fields


def _write_catalog(entry: VendorRegistryEntry, fields: list[EnrichedField], path: Path) -> None:
    doc = {
        "meta": {
            "vendor": entry.slug,
            "resolved_via": "registry",
            "produced_by": "lexicon-discover",
            "produced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "sources": [{"kind": s.kind, "url": s.url} for s in entry.sources],
        },
        "fields": {
            f.name: {
                "description": f.description,
                "unit": f.unit,
                "unit_confidence": round(f.unit_confidence, 2),
                "semantic_tags": [
                    {"tag": t.tag, "weight": round(t.weight, 2)} for t in f.semantic_tags
                ],
                "traps": [
                    {"kind": t.kind, "target": t.target, "evidence": t.evidence}
                    for t in f.traps
                ],
                "sources": [{"url": src.url, "locator": src.locator} for src in f.sources],
            }
            for f in fields
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# DISCOVERED catalog — auto-generated by lexicon.discover.\n"
        + yaml.safe_dump(doc, sort_keys=False)
    )


def _write_proposed(entry: VendorRegistryEntry, proposed, report: str, path: Path) -> None:
    doc = {
        "meta": {
            "vendor": entry.slug,
            "report": report,
            "status": "proposed",
            "produced_by": "lexicon-discover",
            "produced_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        },
        "fields": {name: p.formula for name, p in proposed.items() if p.formula is not None},
        "proposals": {
            name: {
                "proposed": p.formula,
                "confidence": p.confidence,
                "rationale": p.rationale,
                "needs_review": p.needs_review,
                "needs_human": p.needs_review,   # spec §9.5 uses `needs_human`; emit both for compat
                "alternates": p.alternates,
            }
            for name, p in proposed.items()
        },
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# AUTO-PROPOSED mapping — run verify_mapping.py, then have an expert review.\n"
        + yaml.safe_dump(doc, sort_keys=False)
    )


def run_pipeline(
    *,
    entry: VendorRegistryEntry,
    cache: DiskCache,
    llm: LLMClient,   # accepted for symmetry; not used by v1's rule-based enrichers
    catalogs_dir: Path,
    proposed_dir: Path,
    reports_dir: Path,
    report: str = "queue",
) -> PipelineResult:
    all_docs: list[SourceDoc] = []
    source_statuses: list[dict] = []
    for src in entry.sources:
        docs, status = _fetch(src, cache)
        all_docs.extend(docs)
        source_statuses.append(status)

    raws = _extract(all_docs)
    fields = _enrich(raws)
    proposed = propose_mapping(fields, report=report)

    catalog_path  = catalogs_dir / f"{entry.slug}.yaml"
    proposed_path = proposed_dir / f"{entry.slug}.{report}.PROPOSED.yaml"
    report_path   = reports_dir  / f"{entry.slug}.md"

    _write_catalog(entry, fields, catalog_path)
    _write_proposed(entry, proposed, report, proposed_path)

    traps_flat = []
    for f in fields:
        for t in f.traps:
            traps_flat.append({"field": f.name, "kind": t.kind, "target": t.target})
    write_coverage_report(
        vendor_slug=entry.slug, report=report,
        proposals=proposed, sources=source_statuses, traps=traps_flat,
        path=report_path,
    )
    n_found = sum(1 for p in proposed.values() if p.formula is not None)
    return PipelineResult(
        catalog_path=catalog_path,
        proposed_path=proposed_path,
        report_path=report_path,
        n_fields=len(proposed),
        n_found=n_found,
    )
